name: Catkin

on: 
  pull_request:
    branches: 
    - melodic-devel

jobs:
  catkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        tags: franka_ros:melodic
        file: .ci/Dockerfile.melodic
        push: false
      
    - name: Check Format
      uses: addnab/docker-run-action@v3
      with: 
        image: franka_ros:melodic
        options: -v ${{github.workspace}}:/ros/src/franka_ros
        run: |
          catkin config --workspace /ros/ --init --extend /opt/ros/melodic --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          catkin build --workspace /ros/ --no-deps --make-args -- franka
    
    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: franka_ros:melodic
        options: -v ${{github.workspace}}:/ros/src/franka_ros
        run: |
          catkin config --workspace /ros/ --init --extend /opt/ros/melodic --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          catkin build --no-deps --make-args check-format -- franka_control franka_gripper franka_gazebo franka_hw franka_example_controllers franka_visualization
        
    
