name: Catkin

on: 
  pull_request:
    branches: 
    - kinetic-devel
    - melodic-devel
    - noetic-devel
    
jobs:
  catkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Parse ROS Distro
      run: echo "ROS_DISTRO=$(echo ${{ github.event.pull_request.base.ref }} | sed 's/-devel//')" >> $GITHUB_ENV
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        tags: franka_ros:${{ env.ROS_DISTRO }}
        file: .ci/Dockerfile.${{ env.ROS_DISTRO }}
        push: false
      
    - name: Check Format
      uses: addnab/docker-run-action@v3
      with: 
        image: franka_ros:${{ env.ROS_DISTRO }}
        options: -v ${{github.workspace}}:/ros/src/franka_ros
        run: |
          catkin config --workspace /ros/ --init --extend /opt/ros/$ROS_DISTRO --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          catkin build --no-deps --make-args check-format -- franka_control franka_gripper franka_gazebo franka_hw franka_example_controllers franka_visualization
    - name: Check Lint
      uses: addnab/docker-run-action@v3
      with: 
        image: franka_ros:${{ env.ROS_DISTRO }}
        options: -v ${{github.workspace}}:/ros/src/franka_ros
        run: |
          catkin config --workspace /ros/ --init --extend /opt/ros/${{ env.ROS_DISTRO }} --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          catkin build --no-deps --make-args check-tidy -- franka_control franka_gripper franka_gazebo franka_hw franka_example_controllers franka_visualization
          
    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: franka_ros:${{ env.ROS_DISTRO }}
        options: -v ${{github.workspace}}:/ros/src/franka_ros
        run: |
          catkin config --workspace /ros/ --init --extend /opt/ros/$ROS_DISTRO --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          catkin build --workspace /ros/
          
        
    
