name: Test Report

on:
  workflow_run:                    # runs after CI workflow has finished
    workflows: ['CI'] 
    types:     [completed]
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Create Test Report
      uses: dorny/test-reporter@v1
      with:
        artifact:  test-tesults
        name:      ROS-Unit Tests
        path:      '*.xml'           # Path to test results (inside artifact .zip)
        reporter:  java-junit
